# This is the definition of the required ssl certificate for the mail system
# It will be issued by cert-manager

{{- if .Values.certmanager.enabled }}
apiVersion: {{ .Values.certmanager.apiVersion }}
kind: Certificate
metadata:
  name: smtp-{{ include "mailu.fullname" . }}-certificates
spec:
  secretName: smtp-{{ include "mailu.fullname" . }}-certificates
  renewBefore: 1440h # 60d
  commonName: "{{ first (required "hostname" .Values.publicHostnames) }}"
  dnsNames:
  {{- range .Values.hostnames }}
  - "{{ . }}"
  {{- end }}
  issuerRef:
    kind: {{ .Values.certmanager.issuerType }}
    name: {{ .Values.certmanager.publicIssuerName }}
{{- end }}
